# Generated by Django 2.1.7 on 2020-05-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200516_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='text3',
            field=models.CharField(default='link', max_length=255),
            preserve_default=False,
        ),
    ]
